MACOSX_SDK_VERSION: # [osx and x86_64]
  - 10.14 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
  - "10.14" # [osx and x86_64]
channel_sources:
  - conda-forge
channel_targets:
  - tiledb tiledbsoma_dev
python:
  - 3.10.* *_cpython
python_impl:
  - cpython
