{% set name = "tiledbsoma" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    git_url: https://github.com/single-cell-data/TileDB-SOMA.git
    git_rev: b0b91f6d875f71a542859d944aae1fc82c107862

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - make
        - pybind11
      host:
        - tiledb 2.14.*
        - spdlog
      run:
        - tiledb 2.14.*
        - spdlog

  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
      binary_relocation: 
        - lib/python3.10/site-packages/tiledbsoma/libtiledbsoma.*
        - lib/python3.10/site-packages/tiledbsoma/pytiledbsoma.*.so
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
      host:
        - libtiledbsoma {{ version }}
        - pip
        - python
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - pybind11
        - setuptools
        - setuptools_scm
        - spdlog
        - wheel
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - anndata
        - pandas
        - pyarrow
        - scanpy
        - scipy
        - spdlog
        - tiledb-py
    test:
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
