{% set name = "tiledbsoma" %}
{% set version = "1.1.1" %}
{% set sha256 = "a5ee104c326104d2a95777ca4b05f67d3422198879abc06f9269e6e5d101e037" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win or linux32 or py2k]

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb 2.15.*
        - spdlog
      run:
        - tiledb 2.15.*
        - spdlog

  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
      # binary_relocation: 
      #   - lib/python*/site-packages/tiledbsoma/libtiledbsoma.*
      #   - lib/python*/site-packages/tiledbsoma/pytiledbsoma.*.so
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        #- python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        # - pybind11                               # [build_platform != target_platform]
        # - pyarrow 9.0.*                          # [build_platform != target_platform]
        # - numba                                  # [build_platform != target_platform]
        # - scipy                                  # [build_platform != target_platform]
        # - numpy                                  # [build_platform != target_platform]
      host:
        - python
        # - numba
        # - numpy
        - libtiledbsoma {{ version }}
        - pyarrow 9.0.*
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        # - scipy
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - anndata
        - pandas
        - pyarrow 9.0.*
        - 'scanpy>=1.9.2'
        - scipy
        - anndata
        - tiledb-py 0.21.*
        - typing-extensions
        - numba
        - attrs
        - numpy
        # - somacore 1.0.*
    imports:
      - tiledbsoma
    test:
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
