# This pipeline runs nightly. It updates the recipe to build the latest commit
# from "main" in the TileDB-SOMA repo, and force pushes to the branch
# "nightly-build", which triggers the feedstock builds on Azure. Because
# `upload_on_branch: main` is set in `conda-forge.yml`, any binaries produced by
# this nightly test build are never uploaded to anaconda.org
name: Trigger nightly build
on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
     - cron: "27 1 * * *" # Every night at 1:27 AM UTC (8:27 PM EST; 9:27 PM EDT)
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update recipe source to use Git repo
        run: |
          # append "-nightly" to version string
          sed -i \
            s/"{% set version = \"\(.*\)\" %}"/"{% set version = \"\\1-nightly\" %}"/ \
            recipe/meta.yaml

          # Use Git URL as source
          sed -i \
            s/"url: https:\/\/github.com\/single-cell-data\/TileDB-SOMA\/archive\/{{ version }}.tar.gz"/"git_url: https:\/\/github.com\/single-cell-data\/TileDB-SOMA.git"/ \
            recipe/meta.yaml

          # Build the latest commit on "main" branch
          sed -i \
            s/"sha256: .\+"/"git_rev: main\n  git_depth: 1"/ \
            recipe/meta.yaml

          git --no-pager diff recipe/meta.yaml
      - name: Push update to GitHub
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "runneradmin@github.com"
          git commit -am "Nightly build"
          git push --force origin HEAD:nightly-build
